import {
  Boxes,
  ChartColumn,
  Cross,
  FileText,
  Home,
  LayoutDashboard,
  Logs,
  Package,
  Search,
  Settings,
  ShoppingBag,
  Truck,
  Users,
} from "lucide-react";

export const AppIcons = {
  Boxes: Boxes,
  ChartColumn: ChartColumn,
  FileText: FileText,
  Home: Home,
  LayoutDashboard: LayoutDashboard,
  Package: Package,
  Settings: Settings,
  ShoppingBag: ShoppingBag,
  Truck: Truck,
  Users: Users,
  Cross: Cross,
  Logs: Logs,
  Search: Search,
};
